#include <windows.h>
#include <iostream>
#include <vector>
#include <stdio.h>
#include <math.h>
#include <assert.h>
#include <GL/glew.h>
#include <GL/freeglut.h>
#include <CL/cl.h>
#include <CL/cl_gl.h>
#include "DataTypes.h"
#define  RENDERLIB_EXPORTS